apiVersion: apps/v1
kind: Deployment
metadata:
  name: chessgame-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chessgame-ui
  template:
    metadata:
      labels:
        app: chessgame-ui
    spec:
      containers:
        - name: chessgame-ui
          image: chessgame-ui:latest
          ports:
            - containerPort: 5173
          env:
            - name: SERVER_URL
              value: "http://chessgame-server:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: chessgame-ui
spec:
  selector:
    app: chessgame-ui
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer
