services:

  # The Go backend
  chessgame-server:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      - TURSO_DATABASE_URL=${TURSO_DATABASE_URL}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped

  # React frontend
  chessgame-ui:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - chessgame-server
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ../backend/internal/sessionstore/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: unless-stopped
